### PR TITLE
added support for max sentence length

### PR DESCRIPTION
**Pull request by themantalope**

### CODE REVIEW

**Comment by alexcg1** [comment]
How does this work exactly? It breaks a sentence if it's over the max length? I just tested it with a sentence of 80+ characters and no break. Maybe I'm misunderstanding the overlap?

## Experiment

I gave it the sentence:

```
This is a very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very long sentence
```

## Result

It returned the same sentence, unbroken

**Comment by alexcg1** [comment]
Thanks for the PR by the way, and sorry for the late reply. Been a busy few days!

**Comment by themantalope** [comment]
Whoops! Thanks for checking. If you look at the new commit I forgot to make sure that the sentence length was between the min and max length for the default way of adding a chunk. If you run `python executor.py` now  you should see the expected output.

**Comment by themantalope** [comment]
The motivation was because some Jina text encoders out of the box do not handle encoding long sentences.

**Comment by alexcg1** [comment]
Nice. Thanks for this :) I'll merge it now

**Comment by alexcg1** [comment]
btw, what are you using Jina for? I see you're in radiology - we're launching our new Search Apps function which has a chest X-ray demo you can deploy from the web frontend (at cloud.jina.ai)

**Pull request merged**
